default_platform(:ios)

platform :ios do
  lane :build do
    sync_code_signing(type: "development")
    cordova(
      platform: "ios",
      release: false,
      device: true,
      type: "development",
      team_id: "GHPBX39444"
    )
  end
end
