version: '3'

services:
  keycloak:
    image: jboss/keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgresql
      POSTGRES_DB: aerogear_mobile_metrics
  metrics:
    image: aerogear/aerogear-app-metrics
    ports:
      - "3000:3000"
    environment:
      PGHOST: db
      PGUSER: postgresql
      PGPASSWORD: postgres
      PGDATABASE: aerogear_mobile_metrics
    depends_on:
      - db
