version: '3'

services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
  postgres:
    image: postgres:9.6
    container_name: postgres
    volumes:
    - "./config/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql"
    ports:
      - "5432:5432"
  metrics:
    image: aerogear/aerogear-app-metrics
    container_name: metrics
    ports:
      - "3000:3000"
    environment:
      PGHOST: postgres
      PGUSER: metrics
      PGPASSWORD: metrics
      PGDATABASE: metrics
    depends_on:
      - postgres
  ups:
    image: aerogear/unifiedpush-wildfly-plain
    ports:
    - "8089:8080"
    environment:
      POSTGRES_SERVICE_HOST: postgres
      POSTGRES_SERVICE_PORT: 5432
      POSTGRES_USER: ups
      POSTGRES_PASSWORD: ups
      POSTGRES_DATABASE: ups
    depends_on:
      - postgres

networks:
  default:
    external:
      name: aerogear