version: '3'

services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
  metricsdb:
    image: postgres:9.6
    container_name: metricsdb
    environment:
      POSTGRES_USER: metrics	
      POSTGRES_PASSWORD: metrics	
      POSTGRES_DB: metrics
  metrics:
    image: aerogear/aerogear-app-metrics
    container_name: metrics
    ports:
      - "3000:3000"
    environment:
      PGHOST: metricsdb
      PGUSER: metrics
      PGPASSWORD: metrics
      PGDATABASE: metrics
    depends_on:
      - metricsdb
  upsdb:
    image: postgres:9.6
    container_name: upsdb
    environment:
      POSTGRES_USER: ups	
      POSTGRES_PASSWORD: ups	
      POSTGRES_DB: ups
  ups:
    image: aerogear/unifiedpush-wildfly-plain
    ports:
    - "8089:8080"
    environment:
      POSTGRES_SERVICE_HOST: upsdb
      POSTGRES_SERVICE_PORT: 5432
      POSTGRES_USER: ups
      POSTGRES_PASSWORD: ups
      POSTGRES_DATABASE: ups
    depends_on:
      - upsdb

networks:
  default:
    external:
      name: aerogear