CREATE DATABASE ups;
CREATE USER ups WITH PASSWORD 'ups';
GRANT ALL PRIVILEGES ON DATABASE ups TO ups;

CREATE DATABASE metrics;
CREATE USER metrics WITH PASSWORD 'metrics';
GRANT ALL PRIVILEGES ON DATABASE metrics TO metrics;
